package entry

import (
	"context"
	"workshop-platform/backend/internal/domain"
	"workshop-platform/backend/internal/repositories"
)

type RegisterEntryInput struct {
	WorkshopID string
	VehicleID  string
	Mileage    int
	FuelLevel  string
	Notes      string
}

type RegisterEntry struct {
	entryRepo   repositories.EntryRepository
	vehicleRepo repositories.VehicleRepository
}

func NewRegisterEntry(entryRepo repositories.EntryRepository, vehicleRepo repositories.VehicleRepository) *RegisterEntry {
	return &RegisterEntry{entryRepo: entryRepo, vehicleRepo: vehicleRepo}
}

func (uc *RegisterEntry) Execute(ctx context.Context, input RegisterEntryInput) (*domain.WorkshopEntry, error) {
	entry := &domain.WorkshopEntry{
		WorkshopID:  input.WorkshopID,
		VehicleID:   input.VehicleID,
		Mileage:     input.Mileage,
		FuelLevel:   input.FuelLevel,
		Notes:       input.Notes,
		Status:      "received",
		EntryNumber: "", // generated by repo or service
	}
	if err := uc.entryRepo.Create(ctx, entry); err != nil {
		return nil, err
	}
	return entry, nil
}
